stages:
  - build
  - scan

# Build the image with the commit SHA as a tag
build-job:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - echo "Building app image..."
    - docker build -t myapp:$CI_COMMIT_SHA .

# Run Trivy against the built image
trivy_scan:
  stage: scan
  image: aquasec/trivy:latest
  script:
    # Fail pipeline if HIGH or CRITICAL CVEs found
    - trivy image --exit-code 1 --severity HIGH,CRITICAL -f json -o trivy-report.json myapp:$CI_COMMIT_SHA
  allow_failure: false
  artifacts:
    reports:
      dependency_scanning: trivy-report.json
